apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: todo
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: mounika224/todo-k8s-app:latest
        ports:
        - containerPort: 80

