apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008  # Optional: Pick a port between 30000–32767